version: '3'

networks:
  frontend:

volumes:
  vol-db:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/db

  vol-www:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/www

services:
  mariadb:
    build: mariadb/
    container_name: mariadb
    restart: unless-stopped
    expose:
      - 3306
    networks:
      - frontend
    volumes:
      - vol-db:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: wordpress/
    container_name: wordpress
    restart: unless-stopped
    expose:
      - 9000
    networks:
      - frontend
    depends_on:
      - mariadb
    volumes:
      - vol-www:/var/www/html
    env_file:
      - .env

  nginx:
    build: nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    depends_on:
      - wordpress
    volumes:
      - vol-www:/var/www/html
    env_file:
      - .env
