version: '3'
services:

  mariadb:
    build: mariadb/
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - type: volume
        source: db
        target: "/var/lib/mysql"
        read_only: false
    #    - "/tmp/incesql:/var/lib/mysql"
    environment:
      MDB_ROOT_PASS: ${MDB_ROOT_PASS}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}

  nginx:
    build: nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
    depends_on:
      - wordpress
    volumes:
    volumes:
      - type: volume
        source: www
        target: "/var/www/html"
        read_only: false
    environment:
      DOMAIN: ${DOMAIN}

  wordpress:
    build: wordpress/
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - backend
    depends_on:
      - mariadb
    volumes:
      - type: volume
        source: www
        target: "/var/www/html"
        read_only: false
    environment:
      DOMAIN: ${DOMAIN}
      WP_BLOG_NAME: ${WP_BLOG_NAME}
      WP_USR_NAME: ${WP_USR_NAME}
      WP_USR_MAIL: ${WP_USR_MAIL}
      WP_USR_PASS: ${WP_USR_PASS}
      WP_ADM_NAME: ${WP_ADM_NAME}
      WP_ADM_PASS: ${WP_ADM_PASS}
      WP_ADM_MAIL: ${WP_ADM_MAIL}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASS: ${WP_DB_PASS}

volumes:
  www:
    name: www
  db:
    name: db

networks:
  frontend:
    driver: bridge
  backend:
